
CREATE DATABASE Empleados;
USE Empleados;

CREATE TABLE EMPLEADOS (
    DNI INT PRIMARY KEY,
    NOMBRE VARCHAR(10) NOT NULL,
    APELLIDO1 VARCHAR(15) NOT NULL,
    APELLIDO2 VARCHAR(15),
    DIRECC1 VARCHAR(25),
    DIRECC2 VARCHAR(25),
    CIUDAD VARCHAR(20),
    PROVINCIA VARCHAR(20),
    COD_POSTAL VARCHAR(5),
    SEXO CHAR(1) NOT NULL,
    FECHA_NAC DATE,
    CONSTRAINT ck_sexo CHECK (SEXO IN ('H', 'M'))
);

CREATE TABLE DEPARTAMENTOS (
    DPTO_COD INT PRIMARY KEY,
    NOMBRE_DPTO VARCHAR(30) NOT NULL,
    DPTO_PADRE INT,
    PRESUPUESTO DECIMAL(10, 2) NOT NULL,
    PRES_ACTUAL DECIMAL(10, 2),
    CONSTRAINT uk_nombre_dpto UNIQUE (NOMBRE_DPTO)
);
CREATE TABLE ESTUDIOS (
    EMPLEADO_DNI INT,
    UNIVERSIDAD VARCHAR(50) NOT NULL,
    AÑO INT NOT NULL,
    GRADO VARCHAR(3) NOT NULL,
    ESPECIALIDAD VARCHAR(20) NOT NULL,
    PRIMARY KEY (EMPLEADO_DNI, UNIVERSIDAD, AÑO),
    FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI)
);

CREATE TABLE HISTORIAL_LABORAL (
    EMPLEADO_DNI INT,
    TRABAJO_COD INT,
    FECHA_INICIO DATE,
    FECHA_FIN DATE,
    DPTO_COD INT,
    SUPERVISOR_DNI INT,
    PRIMARY KEY (EMPLEADO_DNI, TRABAJO_COD, FECHA_INICIO),
    FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI),
    FOREIGN KEY (DPTO_COD) REFERENCES DEPARTAMENTOS(DPTO_COD),
    FOREIGN KEY (SUPERVISOR_DNI) REFERENCES EMPLEADOS(DNI)
);

CREATE TABLE HISTORIAL_SALARIAL (
    EMPLEADO_DNI INT,
    SALARIO DECIMAL(10, 2) NOT NULL,
    FECHA_COMIENZO DATE NOT NULL,
    FECHA_FIN DATE,
    PRIMARY KEY (EMPLEADO_DNI, FECHA_COMIENZO),
    FOREIGN KEY (EMPLEADO_DNI) REFERENCES EMPLEADOS(DNI)
);

CREATE TABLE UNIVERSIDADES (
    UNIV_COD INT PRIMARY KEY,
    NOMBRE_UNIV VARCHAR(25) NOT NULL,
    CIUDAD VARCHAR(20),
    MUNICIPIO VARCHAR(2),
    COD_POSTAL VARCHAR(5)
);


CREATE TABLE TRABAJOS (
    TRABAJO_COD INT PRIMARY KEY,
    NOMBRE_TRAB VARCHAR(20) NOT NULL,
    SALARIO_MIN DECIMAL(10, 2) NOT NULL,
    SALARIO_MAX DECIMAL(10, 2) NOT NULL,
    CONSTRAINT uk_nombre_trab UNIQUE (NOMBRE_TRAB)
);






